Add a uid/gid flag to spawn a container with non-zero uid/gid.
staticfloat/Sandbox.jl pull request #28
Opened 2021-04-19 07:46 UTC by maleadt

Turns out `tar` behaves differently when `id==0` -- https://github.com/habitat-sh/builder/issues/365#issuecomment-382862233, which doesn't work in the single-user containers we spawn (breaking Artifacts) -- so add an option to create a user map that uses a different uid/gid.

2021-04-19 09:53 UTC, maleadt commented
```
/home/runner/.julia/artifacts/b75badd28f02d9a4824aa829a7537d1c6f39fb13/bin/sandbox: unrecognized option '--uid'
```

Doesn't look like the `build local sandbox` CI is actually using the local sandbox. Presumable `Pkg.test` uses a different environment that ignores the `LocalPreferences.toml`?

2021-04-19 10:02 UTC, giordano commented
> Presumable Pkg.test uses a different environment that ignores the LocalPreferences.toml?

Yes: https://github.com/JuliaLang/Pkg.jl/issues/2500.  You should have a separate [`test/Project.toml`](https://github.com/JuliaMath/FFTW.jl/blob/53fe68911045932f56b77c38c068eab64617f690/test/Project.toml) like `FFTW.jl`

2021-04-19 10:15 UTC, giordano commented on test/Project.toml
> +UserNSSandbox_jll = "b88861f7-1d72-59dd-91e7-a8cc876a4984"
If I understand test-specific projects correctly, you only need to specify the packages you actually use, excluding the current package itself (this is at least what we did in `FFTW.jl`)
```suggestion
Artifacts = "56f22d72-fd6d-98f1-02f0-08ddc0907c33"
Scratch = "6c6a2e73-6563-6170-7368-637461726353"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
```

2021-04-19 10:16 UTC, maleadt commented
Doesn't seem to help here.

2021-04-19 10:18 UTC, giordano commented
Maybe [this](https://github.com/JuliaMath/FFTW.jl/blob/53fe68911045932f56b77c38c068eab64617f690/.github/workflows/CI.yml#L63-L64) is relevant?

2021-04-19 10:19 UTC, maleadt commented
Ah, yes, so that's setting a global preferences. Seems pretty hacky, at this point we could just run `julia --project test/runtests.jl` and just not use `Pkg.test`...

2021-04-19 10:31 UTC, maleadt commented
OK, only legit failures now.

2021-04-19 10:32 UTC, maleadt commented on test/runtests.jl
> +using Test, Sandbox, UserNSSandbox_jll
It's annoying how a project needs to depend on a package for Preferences to pick up the preference. Is that intended?

2021-04-19 11:21 UTC, maleadt commented
OK, all done. How do we want to proceed here? Merge with failures, rebuild UserNSSandbox_jll, and re-run CI to verify?

2021-04-19 20:42 UTC, maleadt commented
@staticfloat, re. https://github.com/staticfloat/Sandbox.jl/issues/24#issuecomment-822747930, I take it you're opposed to this? I don't see an alternative though, `su` or similar doesn't work in the userns, and `id=0` really does make software behave differently.

2021-04-19 22:18 UTC, staticfloat requested changes

2021-04-19 22:22 UTC, staticfloat commented
> I take it you're opposed to this?

Actually, I didn't really think that the patch to `userns_sandbox.c` would be so small, so I'm totally open to this change.  In fact, it may be quite useful for BB to build things as non-root!

2021-04-19 22:23 UTC, giordano commented
>  it may be quite useful for BB to build things as non-root!

I thought having a single user helped with mapping permissions :thinking:

2021-04-19 22:25 UTC, staticfloat commented
Indeed it does, but this nicely dodges the problem by keeping things as a single-user system, it just allows using a UID that is nonzero.  I think we will want to have the BB sandbox default to using the same numeric ID as the originating user, which will even allow us to avoid the `chown` calls we have to make after the Docker runner finishes.

2021-04-20 11:04 UTC, maleadt commented on src/Docker.jl
> +            end
There's details in the commit message. I've created an issue too: https://github.com/JuliaIO/Tar.jl/issues/103

2021-04-20 11:06 UTC, maleadt commented on src/Docker.jl
> +        append!(cmd_string, ["--user", "$(something(config.uid, 0)):$(something(config.gid, 0))"])
Actually, turns out that Docker does support a group-only specification, so we could keep both fields optional. Or have them default to 0 for consistency, same to me.

2021-04-20 13:28 UTC, maleadt commented on test/runtests.jl
> +using Test, Sandbox, UserNSSandbox_jll
Yeah, I (mistakenly) thought you needed the import too.

2021-04-20 20:36 UTC, staticfloat commented
I'm quite happy with this, with the one exception that using `Tar.jl` was one part of the hope that I had that this package would be able to work on Windows without further binary dependencies. :(

I guess we can work towards that in the future, in the `Tar.jl` repo.

2021-04-20 20:36 UTC, merged